-- Journal / Journey archive: entries, ordered media, publication controls, and RLS.

DO $$ BEGIN
  CREATE TYPE public.journal_entry_type AS ENUM (
    'journal',
    'photo_dump',
    'on_the_road',
    'studio',
    'release_notes',
    'behind_the_scenes',
    'personal',
    'milestone'
  );
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE public.journal_status AS ENUM ('draft', 'scheduled', 'published', 'archived');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE public.journal_media_kind AS ENUM ('image', 'video');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

CREATE TABLE public.journal_entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  entry_number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  slug text NOT NULL UNIQUE
    CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' AND char_length(slug) <= 120),
  title text NOT NULL CHECK (char_length(title) BETWEEN 1 AND 180),
  excerpt text CHECK (char_length(excerpt) <= 500),
  entry_type public.journal_entry_type NOT NULL DEFAULT 'journal',
  status public.journal_status NOT NULL DEFAULT 'draft',
  content jsonb NOT NULL DEFAULT '{"version":1,"blocks":[]}'::jsonb
    CHECK (
      jsonb_typeof(content) = 'object'
      AND content ->> 'version' = '1'
      AND jsonb_typeof(content -> 'blocks') = 'array'
    ),
  event_date date,
  location text CHECK (char_length(location) <= 160),
  published_at timestamptz,
  featured_at timestamptz,
  seo_title text CHECK (char_length(seo_title) <= 70),
  seo_description text CHECK (char_length(seo_description) <= 180),
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (status NOT IN ('published', 'scheduled') OR published_at IS NOT NULL),
  CHECK (featured_at IS NULL OR status = 'published')
);

CREATE TABLE public.journal_media (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  entry_id uuid NOT NULL REFERENCES public.journal_entries(id) ON DELETE CASCADE,
  storage_path text NOT NULL UNIQUE
    CHECK (storage_path ~ '^[0-9a-f-]{36}/[A-Za-z0-9._-]+$' AND char_length(storage_path) <= 500),
  kind public.journal_media_kind NOT NULL DEFAULT 'image',
  mime_type text NOT NULL CHECK (mime_type IN ('image/jpeg', 'image/png', 'image/webp', 'image/avif', 'video/mp4')),
  width integer CHECK (width IS NULL OR width > 0),
  height integer CHECK (height IS NULL OR height > 0),
  file_size_bytes bigint CHECK (file_size_bytes IS NULL OR file_size_bytes > 0),
  blur_data_url text CHECK (char_length(blur_data_url) <= 1000),
  alt_text text CHECK (char_length(alt_text) <= 500),
  caption text CHECK (char_length(caption) <= 1000),
  credit text CHECK (char_length(credit) <= 300),
  sort_order integer NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT journal_media_entry_sort_unique
    UNIQUE (entry_id, sort_order) DEFERRABLE INITIALLY DEFERRED
);

ALTER TABLE public.journal_entries
  ADD COLUMN cover_media_id uuid REFERENCES public.journal_media(id) ON DELETE SET NULL,
  ADD COLUMN og_media_id uuid REFERENCES public.journal_media(id) ON DELETE SET NULL;

CREATE INDEX journal_entries_public_archive_idx
  ON public.journal_entries (published_at DESC, entry_number DESC)
  WHERE status IN ('published', 'scheduled');

CREATE INDEX journal_entries_type_archive_idx
  ON public.journal_entries (entry_type, published_at DESC)
  WHERE status IN ('published', 'scheduled');

CREATE UNIQUE INDEX journal_entries_one_featured
  ON public.journal_entries ((true))
  WHERE featured_at IS NOT NULL AND status = 'published';

CREATE INDEX journal_media_entry_order_idx
  ON public.journal_media (entry_id, sort_order);

CREATE TRIGGER tr_journal_entries_updated_at
  BEFORE UPDATE ON public.journal_entries
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER tr_journal_media_updated_at
  BEFORE UPDATE ON public.journal_media
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE OR REPLACE FUNCTION public.validate_journal_publication()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  IF NEW.status = 'scheduled'
    AND NEW.published_at <= now()
    AND (
      TG_OP = 'INSERT'
      OR OLD.status IS DISTINCT FROM 'scheduled'
      OR OLD.published_at IS DISTINCT FROM NEW.published_at
    )
  THEN
    RAISE EXCEPTION 'Scheduled publication time must be in the future' USING ERRCODE = '23514';
  END IF;

  IF NEW.status IN ('published', 'scheduled') AND EXISTS (
    SELECT 1
    FROM public.journal_media media
    WHERE media.entry_id = NEW.id
      AND media.kind = 'image'
      AND coalesce(btrim(media.alt_text), '') = ''
  ) THEN
    RAISE EXCEPTION 'Every published Journal image requires alt text' USING ERRCODE = '23514';
  END IF;

  IF NEW.cover_media_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.journal_media media
    WHERE media.id = NEW.cover_media_id AND media.entry_id = NEW.id
  ) THEN
    RAISE EXCEPTION 'Cover media must belong to the same Journal entry' USING ERRCODE = '23514';
  END IF;

  IF NEW.og_media_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.journal_media media
    WHERE media.id = NEW.og_media_id AND media.entry_id = NEW.id
  ) THEN
    RAISE EXCEPTION 'Open Graph media must belong to the same Journal entry' USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER tr_validate_journal_publication
  BEFORE INSERT OR UPDATE OF status, published_at, cover_media_id, og_media_id ON public.journal_entries
  FOR EACH ROW EXECUTE FUNCTION public.validate_journal_publication();

CREATE OR REPLACE FUNCTION public.validate_journal_media_alt()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  IF NEW.kind = 'image'
    AND coalesce(btrim(NEW.alt_text), '') = ''
    AND EXISTS (
      SELECT 1 FROM public.journal_entries entry
      WHERE entry.id = NEW.entry_id
        AND entry.status IN ('published', 'scheduled')
    )
  THEN
    RAISE EXCEPTION 'Every published Journal image requires alt text' USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER tr_validate_journal_media_alt
  BEFORE INSERT OR UPDATE OF kind, alt_text, entry_id ON public.journal_media
  FOR EACH ROW EXECUTE FUNCTION public.validate_journal_media_alt();

CREATE OR REPLACE FUNCTION public.set_featured_journal_entry(target_id uuid)
RETURNS public.journal_entries
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  selected_entry public.journal_entries;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Administrator access required' USING ERRCODE = '42501';
  END IF;

  SELECT * INTO selected_entry
  FROM public.journal_entries
  WHERE id = target_id
  FOR UPDATE;

  IF selected_entry.id IS NULL THEN
    RAISE EXCEPTION 'Journal entry not found' USING ERRCODE = 'P0002';
  END IF;

  IF selected_entry.status <> 'published' OR selected_entry.published_at > now() THEN
    RAISE EXCEPTION 'Only a currently published Journal entry can be featured' USING ERRCODE = '23514';
  END IF;

  UPDATE public.journal_entries
  SET featured_at = NULL
  WHERE featured_at IS NOT NULL AND id <> target_id;

  UPDATE public.journal_entries
  SET featured_at = now()
  WHERE id = target_id
  RETURNING * INTO selected_entry;

  RETURN selected_entry;
END;
$$;

CREATE OR REPLACE FUNCTION public.reorder_journal_media(target_entry_id uuid, ordered_ids uuid[])
RETURNS SETOF public.journal_media
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Administrator access required' USING ERRCODE = '42501';
  END IF;

  IF cardinality(ordered_ids) IS NULL OR cardinality(ordered_ids) = 0 THEN
    RAISE EXCEPTION 'Media order cannot be empty' USING ERRCODE = '23514';
  END IF;

  IF (SELECT count(DISTINCT id) FROM unnest(ordered_ids) AS id) <> cardinality(ordered_ids) THEN
    RAISE EXCEPTION 'Media order contains duplicate ids' USING ERRCODE = '23514';
  END IF;

  IF (
    SELECT count(*) FROM public.journal_media WHERE entry_id = target_entry_id
  ) <> cardinality(ordered_ids)
  OR EXISTS (
    SELECT 1
    FROM unnest(ordered_ids) AS requested(id)
    LEFT JOIN public.journal_media media
      ON media.id = requested.id AND media.entry_id = target_entry_id
    WHERE media.id IS NULL
  ) THEN
    RAISE EXCEPTION 'Media order must contain every entry media id exactly once' USING ERRCODE = '23514';
  END IF;

  UPDATE public.journal_media media
  SET sort_order = requested.ordinality - 1
  FROM unnest(ordered_ids) WITH ORDINALITY AS requested(id, ordinality)
  WHERE media.id = requested.id AND media.entry_id = target_entry_id;

  RETURN QUERY
  SELECT * FROM public.journal_media
  WHERE entry_id = target_entry_id
  ORDER BY sort_order;
END;
$$;

ALTER TABLE public.journal_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.journal_media ENABLE ROW LEVEL SECURITY;

CREATE POLICY journal_entries_public_select
  ON public.journal_entries
  FOR SELECT
  TO anon, authenticated
  USING (status IN ('published', 'scheduled') AND published_at <= now());

CREATE POLICY journal_entries_admin_select
  ON public.journal_entries
  FOR SELECT
  TO authenticated
  USING (public.is_admin());

CREATE POLICY journal_entries_admin_insert
  ON public.journal_entries
  FOR INSERT
  TO authenticated
  WITH CHECK (public.is_admin());

CREATE POLICY journal_entries_admin_update
  ON public.journal_entries
  FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

CREATE POLICY journal_entries_admin_delete
  ON public.journal_entries
  FOR DELETE
  TO authenticated
  USING (public.is_admin());

CREATE POLICY journal_media_public_select
  ON public.journal_media
  FOR SELECT
  TO anon, authenticated
  USING (EXISTS (
    SELECT 1
    FROM public.journal_entries entry
    WHERE entry.id = journal_media.entry_id
      AND entry.status IN ('published', 'scheduled')
      AND entry.published_at <= now()
  ));

CREATE POLICY journal_media_admin_select
  ON public.journal_media
  FOR SELECT
  TO authenticated
  USING (public.is_admin());

CREATE POLICY journal_media_admin_insert
  ON public.journal_media
  FOR INSERT
  TO authenticated
  WITH CHECK (public.is_admin());

CREATE POLICY journal_media_admin_update
  ON public.journal_media
  FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

CREATE POLICY journal_media_admin_delete
  ON public.journal_media
  FOR DELETE
  TO authenticated
  USING (public.is_admin());

REVOKE ALL ON TABLE public.journal_entries, public.journal_media FROM anon, authenticated;
GRANT SELECT ON TABLE public.journal_entries, public.journal_media TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.journal_entries, public.journal_media TO authenticated;
GRANT ALL ON TABLE public.journal_entries, public.journal_media TO service_role;
GRANT USAGE ON TYPE public.journal_entry_type, public.journal_status, public.journal_media_kind TO anon, authenticated;
GRANT USAGE ON TYPE public.journal_entry_type, public.journal_status, public.journal_media_kind TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.journal_entries_entry_number_seq TO authenticated, service_role;

-- Current Supabase projects no longer auto-grant Data API privileges for SQL-created tables.
-- Make the existing schema's RLS policies reachable without broadening their row access.
GRANT SELECT ON TABLE
  public.shows,
  public.releases,
  public.tracks,
  public.media_items,
  public.press_items,
  public.social_links,
  public.site_settings
TO anon;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
  public.admin_users,
  public.vip_members,
  public.shows,
  public.releases,
  public.tracks,
  public.media_items,
  public.press_items,
  public.social_links,
  public.booking_inquiries,
  public.site_settings
TO authenticated;

GRANT ALL ON TABLE
  public.admin_users,
  public.vip_members,
  public.shows,
  public.releases,
  public.tracks,
  public.media_items,
  public.press_items,
  public.social_links,
  public.booking_inquiries,
  public.site_settings
TO service_role;

REVOKE ALL ON FUNCTION public.is_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;

REVOKE ALL ON FUNCTION public.set_featured_journal_entry(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.set_featured_journal_entry(uuid) TO authenticated;

REVOKE ALL ON FUNCTION public.reorder_journal_media(uuid, uuid[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.reorder_journal_media(uuid, uuid[]) TO authenticated;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'journal-media',
  'journal-media',
  false,
  26214400,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/avif', 'video/mp4']
)
ON CONFLICT (id) DO UPDATE SET
  public = false,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

CREATE POLICY journal_media_storage_admin_select
  ON storage.objects
  FOR SELECT
  TO authenticated
  USING (bucket_id = 'journal-media' AND public.is_admin());

CREATE POLICY journal_media_storage_admin_insert
  ON storage.objects
  FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'journal-media'
    AND public.is_admin()
    AND (storage.foldername(name))[1] ~ '^[0-9a-f-]{36}$'
  );

CREATE POLICY journal_media_storage_admin_update
  ON storage.objects
  FOR UPDATE
  TO authenticated
  USING (bucket_id = 'journal-media' AND public.is_admin())
  WITH CHECK (
    bucket_id = 'journal-media'
    AND public.is_admin()
    AND (storage.foldername(name))[1] ~ '^[0-9a-f-]{36}$'
  );

CREATE POLICY journal_media_storage_admin_delete
  ON storage.objects
  FOR DELETE
  TO authenticated
  USING (bucket_id = 'journal-media' AND public.is_admin());
